### ISSUE TITLE
Getting error during qBittorrent connection attempt

### ISSUE THREAD

**Issue by donnielrt** [ccf-2012/seedcross#23]
Hi, 

I'm getting the following error when attempting to start cross seeding the first time:

```
Starting at:03/20/2023, 01:32:25
Connecting: 127.0.0.1
There was an error during auth_log_in: APIConnectionError('Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host=\'127.0.0.1\', port=9128): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError(\'
```

I've configured qBittorrent's Web UI settings and have confirmed that I'm using the right username, password, hostname and port. I'm running seedcross on Docker in Windows 10. I've configured it to use the API key from Prowlarr.

Does seedcross try to connect to qBittorrent using https? I don't have a local https certificate for its web UI.

**Comment by Hayajiro** [comment]
You probably resolved this already, but the issue is that `localhost` (`127.0.0.1`) in the Docker container is not the same as `localhost` on your host system. You need to use the IP / hostname of whatever container / host qbit is running on. Google should help you find the details when searching for something like `docker windows get host ip`. I'm not a Windows-Guy so YMMV.

**Comment by donnielrt** [comment]
Thanks! Yup, I'd managed to get this working, I'll close the issue.
